services:
  app:
    build: .
    container_name: url_shortener_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      APP_PORT: 8080
      DB_URL: postgres://postgres:password@db:5432/url_db?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_DB: 0
    restart: always

  db:
    image: postgres:15
    container_name: url_shortener_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: url_shortener_redis
    restart: always
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    container_name: url_shortener_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data: